### ISSUE TITLE
Error handling for .readlines() and url global variable declaration

### ISSUE THREAD

**Issue by gdfurr98** [hanicraft/CpanelBruteforce#1]
I had to edit this script a little to get it to work on my machine. First, I needed to add the argument " errors='replace' " to the open function which takes the wordlist and I needed to explicitly declare "url" as a global variable in the main() function.

**Comment by hanijanaty2006** [comment]
ok i will fix it

**Comment by miloshahpk** [comment]
Traceback (most recent call last):
  File "/home/milo-kali/CpanelBruteforce/CPanelBruteForce.py", line 63, in <module>
    main()
  File "/home/milo-kali/CpanelBruteforce/CPanelBruteForce.py", line 32, in main
    passwords = passfile.readlines()
                ^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

Whenever i try to execute it gives me this error.

**Comment by cepicdalim** [comment]
Here it's my fork that cover mentioned fixes. https://github.com/cepicdalim/CpanelBruteforce
